name: publish to dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: set the bloody FA Key
        run: scripts/set_the_bloody_fa_pro_key.sh
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_PRO_KEY }}
      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: Lint
        uses: CultureHQ/actions-yarn@master
        with:
          args: lint
      - name: Build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build --mode development
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.5.3
        if: github.ref == 'refs/heads/dev'
        with:
          local: dist/
          remote: /var/www/dev/
          host: dev.crisis.app
          username: ${{ secrets.FTP_USERNAME }}
          privateKey: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          passphrase: ${{ secrets. DEPLOY_KEY_PASSWORD }}
